---
sidebar: sidebar 
permalink: check-clone-integrity.html 
keywords: integrity check, data corruption 
summary: Führen Sie eine Integritätsprüfung durch, um festzustellen, ob die Sandbox-Klondaten in NetApp Workload Factory für Datenbanken intakt oder beschädigt sind. 
---
= Überprüfen Sie die Integrität der Daten in einem Sandbox-Klon
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Führen Sie eine Integritätsprüfung durch, um festzustellen, ob die Sandbox-Klondaten in NetApp Workload Factory für Datenbanken intakt oder beschädigt sind.

.Über diese Aufgabe
Wenn Sie einen Sandbox-Klon von einer Quelldatenbank erstellen, während diese beschäftigt ist, sind die Daten des Klons möglicherweise nicht mit dem neuesten Snapshot der Quelldatenbank synchronisiert. Dieser Vorgang überprüft die Integrität aller Objekte im Sandbox-Klon und stellt fest, ob die Sandbox-Klondaten aktuell sind.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im Menü „Datenbanken“ die Option „Sandboxen“ aus.
. Wählen Sie in Sandboxen das Aktionsmenü des Sandbox-Klons aus, für den Sie die Integrität überprüfen möchten.
. Wählen Sie *Integritätsprüfung ausführen*.
. Klicken Sie im Dialogfeld Integritätsprüfung auf *Integritätsprüfung*.
. Überprüfen Sie den Status der Integritätsprüfung in Sandboxes oder in der Jobüberwachung.


Wenn die Integritätsprüfung fehlschlägt, empfehlen wir, den Sandbox-Klon nicht zu verwenden und einen neuen Sandbox-Klon zu erstellen.
