---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: Erstellen Sie einen neuen PostgreSQL SQL-Server innerhalb von NetApp Workload Factory für Datenbanken. 
---
= Erstellen Sie einen PostgreSQL-Server in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Zum Erstellen eines neuen PostgreSQL-Servers oder Datenbankhosts in NetApp Workload Factory für Datenbanken sind eine FSx für die ONTAP Dateisystembereitstellung und Ressourcen für Active Directory erforderlich.



== Über diese Aufgabe

Informieren Sie sich vor dem Erstellen eines PostgreSQL-Servers aus Workload Factory über die verfügbaren Speicherbereitstellungstypen für die Datenbankhostkonfiguration, die Betriebsmodi von Workload Factory und die Anforderungen zum Abschließen dieses Vorgangs.

.FSX für ONTAP-File-System-Implementierungen
Die Erstellung eines neuen PostgreSQL-Servers erfordert ein FSX für ONTAP-Dateisystem als Storage-Backend. Sie können ein bestehendes FSX für ONTAP-Dateisystem verwenden oder ein neues Dateisystem erstellen. Wenn Sie ein bestehendes FSX für ONTAP-Dateisystem als Datenbankserver-Storage-Back-End auswählen, erstellen wir eine neue Storage-VM für die PostgreSQL-Workloads.

+ FSx für ONTAP Dateisysteme verfügt über zwei PostgreSQL-Serverbereitstellungsmodelle: _High Availability (HA)_ oder _Einzelinstanz_.  Je nach ausgewähltem FSx for ONTAP -Bereitstellungsmodell werden unterschiedliche Ressourcen für das FSx for ONTAP -Dateisystem erstellt.

* *Bereitstellung von Hochverfügbarkeit*: Ein Dateisystem mit mehreren Verfügbarkeitszonen FSX für NetApp ONTAP wird bereitgestellt, wenn ein neues Dateisystem FSX für ONTAP für die Bereitstellung von Hochverfügbarkeit ausgewählt wird. Separate Volumes und LUNs werden für Daten-, Protokoll- und tempdb-Dateien für eine HA-Implementierung erstellt. Ein zusätzliches Volume und eine LUN werden für Quorum oder Witness Disk für Windows Cluster erstellt. DIE HA-Bereitstellung konfiguriert die Streaming-Replikation zwischen dem primären und dem sekundären PostgreSQL-Server.
* *Einzelinstanzbereitstellung*: Ein Einzelverfügbarkeitszonen-FSX für ONTAP-Dateisystem wird erstellt, wenn ein neuer PostgreSQL-Server erstellt wird. Darüber hinaus werden separate Volumes und LUNs für Daten-, Protokoll- und tempdb-Dateien erstellt.




== Bevor Sie beginnen

Du musst haben link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Berechtigungen zum Erstellen des Datenbankhosts erteilen"^] Erstellen Sie in Ihrem AWS-Konto einen neuen Datenbankhost in Workload Factory.



== Erstellen Sie einen PostgreSQL-Server

Sie können die Bereitstellungsmodi _Quick create_ oder _Advanced create_ verwenden, um diese Aufgabe in der Workload Factory mit den Berechtigungen _Automate_ zu erledigen. Die Codebox bietet auch folgende Tools: REST-API, AWS-CLI, AWS CloudFormation und Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Erfahren Sie, wie Sie Codebox für die Automatisierung verwenden"^].


NOTE: Bei der Verwendung von Terraform aus der Codebox werden der Code, den Sie kopieren oder herunterladen, ausgeblendet `fsxadmin` und `vsadmin` Passwörter. Sie müssen die Passwörter erneut eingeben, wenn Sie den Code ausführen. Zusätzlich zu den _Automate_-Modus-Berechtigungen müssen Sie die folgenden Berechtigungen für das Benutzerkonto hinzufügen: `iam:TagRole` Und `iam:TagInstanceProfile`. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#use-terraform-from-codebox["Lernen Sie die Verwendung von Terraform von Codebox"^].

[role="tabbed-block"]
====
.Schnelle Erstellung
--

NOTE: In _Quick Create_ ist HA das Standardbereitgabemodell, Windows 2016 die Standardversion von Windows und SQL 2019 Standard Edition die Standardversion von SQL.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Datenbanken“ die Option „Host bereitstellen“ und dann im Menü „PostgreSQL-Server“ aus.
. Wählen Sie *Schnellerstelle*.
. Geben Sie unter *Landezone* Folgendes an:
+
.. *AWS Credentials*: Wählen Sie AWS Credentials mit Automatisierungsberechtigungen aus, um den neuen Datenbank-Host bereitzustellen.
+
AWS-Anmeldeinformationen mit Lese-/Schreibberechtigungen ermöglichen der Workload Factory die Bereitstellung und Verwaltung des neuen Datenbankhosts von Ihrem AWS-Konto innerhalb der Workload Factory.

+
Mit AWS-Anmeldeinformationen mit Nur-Lese-Berechtigungen kann die Workload Factory eine CloudFormation-Vorlage generieren, die Sie in der AWS CloudFormation-Konsole verwenden können.

+
Wenn Sie keine AWS-Anmeldeinformationen in der Workload Factory haben und den neuen Server in der Workload Factory erstellen möchten, folgen Sie *Option 1*, um zur Seite Anmeldedaten zu gelangen. Fügen Sie die erforderlichen Anmeldeinformationen und Berechtigungen für den Lese-/Schreibmodus für Datenbank-Workloads manuell hinzu.

+
Wenn Sie das Formular zum Erstellen eines neuen Servers in der Workload Factory ausfüllen möchten, damit Sie eine vollständige YAML-Dateivorlage für die Bereitstellung in AWS CloudFormation herunterladen können, folgen Sie *Option 2*, um sicherzustellen, dass Sie über die erforderlichen Berechtigungen zum Erstellen des neuen Servers in AWS CloudFormation verfügen. Fügen Sie die erforderlichen Anmeldeinformationen und Berechtigungen für den schreibgeschützten Modus für Datenbank-Workloads manuell hinzu.

+
Optional können Sie eine teilweise ausgefüllte YAML-Dateivorlage aus der Codebox herunterladen, um den Stack außerhalb der Workload Factory ohne Anmeldeinformationen oder Berechtigungen zu erstellen. Wählen Sie *CloudFormation* aus der Dropdown-Liste in der Codebox aus, um die YAML-Datei herunterzuladen.

.. *Region & VPC*: Wählen Sie eine Region und ein VPC-Netzwerk.
+
Stellen Sie sicher, dass Sicherheitsgruppen für einen vorhandenen Schnittstellenendpunkt den Zugriff auf das HTTPS-Protokoll (443) auf die ausgewählten Subnetze ermöglichen.

+
AWS-Serviceschnittstellen-Endpunkte (SQS, FSX, EC2, CloudWatch, CloudFormation, SSM) und der S3-Gateway-Endpunkt werden während der Bereitstellung erstellt, wenn nicht gefunden.

+
VPC-DNS-Attribute `EnableDnsSupport` und `EnableDnsHostnames` werden geändert, um die Auflösung der Endpunktadresse zu aktivieren, wenn sie nicht bereits auf festgelegt sind `true`.

.. *Verfügbarkeitszonen*: Wählen Sie Verfügbarkeitszonen und Subnetze aus.
+

NOTE: HA-Implementierungen werden nur in Konfigurationen mit Multiple Availability Zone (MAZ) FSX for ONTAP unterstützt.

+
Subnetze sollten für hohe Verfügbarkeit nicht dieselbe Routentabelle verwenden.

+
... Wählen Sie im Feld *Clusterkonfiguration - Knoten 1* die primäre Verfügbarkeitszone für die MAZ FSX for ONTAP-Konfiguration aus dem Dropdown-Menü *Verfügbarkeitszone* und ein Subnetz aus der primären Verfügbarkeitszone aus dem Dropdown-Menü *Subnetz* aus.
... Wählen Sie im Feld *Cluster-Konfiguration - Knoten 2* die sekundäre Verfügbarkeitszone für die MAZ FSX for ONTAP-Konfiguration aus dem Dropdown-Menü *Verfügbarkeitszone* und ein Subnetz aus der sekundären Verfügbarkeitszone aus dem Dropdown-Menü *Subnetz* aus.




. Geben Sie unter *Anwendungseinstellungen* einen Benutzernamen und ein Passwort für *Datenbankanmeldeinformationen* ein.
. Wählen Sie unter *Connectivity* ein Schlüsselpaar aus, um eine sichere Verbindung zu Ihrer Instanz herzustellen.
. Geben Sie unter *Infrastruktur-Einstellungen* Folgendes an:
+
.. *FSX für ONTAP-System*: Erstellen Sie ein neues FSX für ONTAP-Dateisystem oder verwenden Sie ein vorhandenes FSX für ONTAP-Dateisystem.
+
... * Erstellen Sie ein neues FSX für ONTAP*: Geben Sie Benutzernamen und Passwort ein.
+
Ein neues FSX für ONTAP-Dateisystem kann 30 Minuten oder mehr der Installationszeit hinzufügen.

... *Wählen Sie ein vorhandenes FSX für ONTAP*: Wählen Sie FSX für ONTAP-Namen aus dem Dropdown-Menü und geben Sie einen Benutzernamen und ein Passwort für das Dateisystem ein.
+
Stellen Sie für vorhandene FSX for ONTAP-Dateisysteme Folgendes sicher:

+
**** Die an FSX for ONTAP angeschlossene Routinggruppe ermöglicht die Verwendung von Routen zu den Subnetzen für die Bereitstellung.
**** Die Sicherheitsgruppe ermöglicht Datenverkehr aus den für die Bereitstellung verwendeten Subnetzen, insbesondere HTTPS- (443) und iSCSI- (3260) TCP-Ports.




.. *Größe des Datenlaufwerks*: Geben Sie die Kapazität des Datenlaufwerks ein und wählen Sie die Kapazitätseinheit aus.


. Zusammenfassung:
+
.. *Voreinstellung Vorschau*: Überprüfen Sie die Standardkonfigurationen, die von Quick Create festgelegt wurden.
.. *Geschätzte Kosten*: Gibt eine Schätzung der Kosten an, die Ihnen entstehen könnten, wenn Sie die angezeigten Ressourcen bereitgestellt haben.


. Klicken Sie Auf *Erstellen*.
+
Alternativ können Sie, wenn Sie jetzt eine dieser Standardeinstellungen ändern möchten, den Datenbankserver mit Advanced Create erstellen.

+
Sie können auch *Konfiguration speichern* auswählen, um den Host später bereitzustellen.



--
.Erweiterte Erstellung
--
.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel „Datenbanken“ die Option „Host bereitstellen“ und dann im Menü „PostgreSQL-Server“ aus.
. Wählen Sie *Advanced Create*.
. Wählen Sie unter *Deployment model* *Standalone Instance* oder *High Availability (HA)* aus.
. Geben Sie unter *Landezone* Folgendes an:
+
.. *AWS Credentials*: Wählen Sie AWS Credentials mit Automatisierungsberechtigungen aus, um den neuen Datenbank-Host bereitzustellen.
+
AWS Zugangsdaten mit _Automate_ Berechtigungen ermöglichen die werkseitige Implementierung und das Management des neuen Datenbank-Hosts über Ihr AWS-Konto innerhalb der Workload-Fabrik.

+
Mit AWS-Anmeldeinformationen mit Nur-Lese-Berechtigungen kann die Workload Factory eine CloudFormation-Vorlage generieren, die Sie in der AWS CloudFormation-Konsole verwenden können.

+
Wenn Sie keine AWS-Anmeldeinformationen in der Workload Factory haben und den neuen Server in der Workload Factory erstellen möchten, folgen Sie *Option 1*, um zur Seite Anmeldedaten zu gelangen. Fügen Sie die erforderlichen Anmeldeinformationen und Berechtigungen für den Lese-/Schreibmodus für Datenbank-Workloads manuell hinzu.

+
Wenn Sie das Formular zum Erstellen eines neuen Servers in der Workload Factory ausfüllen möchten, damit Sie eine vollständige YAML-Dateivorlage für die Bereitstellung in AWS CloudFormation herunterladen können, folgen Sie *Option 2*, um sicherzustellen, dass Sie über die erforderlichen Berechtigungen zum Erstellen des neuen Servers in AWS CloudFormation verfügen. Fügen Sie die erforderlichen Anmeldeinformationen und Berechtigungen für den schreibgeschützten Modus für Datenbank-Workloads manuell hinzu.

+
Optional können Sie eine teilweise ausgefüllte YAML-Dateivorlage aus der Codebox herunterladen, um den Stack außerhalb der Workload Factory ohne Anmeldeinformationen oder Berechtigungen zu erstellen. Wählen Sie *CloudFormation* aus der Dropdown-Liste in der Codebox aus, um die YAML-Datei herunterzuladen.

.. *Region & VPC*: Wählen Sie eine Region und ein VPC-Netzwerk.
+
Stellen Sie sicher, dass Sicherheitsgruppen für einen vorhandenen Schnittstellenendpunkt den Zugriff auf das HTTPS-Protokoll (443) auf die ausgewählten Subnetze ermöglichen.

+
AWS-Service-Schnittstellen-Endpunkte (SQS, FSX, EC2, CloudWatch, Cloud-Bildung, SSM) und S3-Gateway-Endpunkt werden während der Implementierung erstellt, wenn nicht gefunden wird.

+
VPC-DNS-Attribute `EnableDnsSupport` und `EnableDnsHostnames` werden geändert, um Auflösung der Endpunktadresse zu aktivieren, falls nicht bereits auf gesetzt `true`.

.. *Verfügbarkeitszonen*: Wählen Sie Verfügbarkeitszonen und Subnetze aus.
+
*Für Einzelinstanzbereitstellungen*

+
Wählen Sie im Feld *Cluster-Konfiguration - Knoten 1* eine Verfügbarkeitszone aus dem Dropdown-Menü *Verfügbarkeitszone* und ein Subnetz aus dem Dropdown-Menü *Subnetz* aus.

+
*Für HA-Bereitstellungen*

+
... Wählen Sie im Feld *Clusterkonfiguration - Knoten 1* die primäre Verfügbarkeitszone für die MAZ FSX for ONTAP-Konfiguration aus dem Dropdown-Menü *Verfügbarkeitszone* und ein Subnetz aus der primären Verfügbarkeitszone aus dem Dropdown-Menü *Subnetz* aus.
... Wählen Sie im Feld *Cluster-Konfiguration - Knoten 2* die sekundäre Verfügbarkeitszone für die MAZ FSX for ONTAP-Konfiguration aus dem Dropdown-Menü *Verfügbarkeitszone* und ein Subnetz aus der sekundären Verfügbarkeitszone aus dem Dropdown-Menü *Subnetz* aus.


.. *Sicherheitsgruppe*: Wählen Sie eine vorhandene Sicherheitsgruppe aus oder erstellen Sie eine neue Sicherheitsgruppe.
+
Während der Implementierung eines neuen Servers werden zwei Sicherheitsgruppen mit den SQL Nodes (EC2 Instanzen) verbunden.

+
... Eine Sicherheitsgruppe für Workloads wird erstellt, um die für PostgreSQL erforderlichen Ports und Protokolle zu ermöglichen.
... Für ein neues FSX für ONTAP-Dateisystem wird eine neue Sicherheitsgruppe erstellt und an den SQL-Knoten angehängt. Für ein vorhandenes FSX for ONTAP-Dateisystem wird die ihm zugeordnete Sicherheitsgruppe automatisch zum PostgreSQL-Knoten hinzugefügt, der die Kommunikation mit dem Dateisystem ermöglicht.




. Geben Sie unter *Anwendungseinstellungen* Folgendes an:
+
.. Wählen Sie das *Betriebssystem* aus dem Dropdown-Menü aus.
.. Wählen Sie die *PostgreSQL-Version* aus dem Dropdown-Menü aus.
.. *Datenbankservername*: Geben Sie den Namen des Datenbank-Clusters ein.
.. *Datenbankanmeldeinformationen*: Geben Sie einen Benutzernamen und ein Passwort für ein neues Dienstkonto ein oder verwenden Sie vorhandene Dienstkontoanmeldeinformationen im Active Directory.


. Wählen Sie unter *Connectivity* ein Schlüsselpaar aus, um eine sichere Verbindung zu Ihrer Instanz herzustellen.
. Geben Sie unter *Infrastruktur-Einstellungen* Folgendes an:
+
.. *DB Instanztyp*: Wählen Sie den Typ der Datenbankinstanz aus dem Dropdown-Menü aus.
.. *FSX für ONTAP-System*: Erstellen Sie ein neues FSX für ONTAP-Dateisystem oder verwenden Sie ein vorhandenes FSX für ONTAP-Dateisystem.
+
... * Erstellen Sie ein neues FSX für ONTAP*: Geben Sie Benutzernamen und Passwort ein.
+
Ein neues FSX für ONTAP-Dateisystem kann 30 Minuten oder mehr der Installationszeit hinzufügen.

... *Wählen Sie ein vorhandenes FSX für ONTAP*: Wählen Sie FSX für ONTAP-Namen aus dem Dropdown-Menü und geben Sie einen Benutzernamen und ein Passwort für das Dateisystem ein.
+
Stellen Sie für vorhandene FSX for ONTAP-Dateisysteme Folgendes sicher:

+
**** Die an FSX for ONTAP angeschlossene Routinggruppe ermöglicht die Verwendung von Routen zu den Subnetzen für die Bereitstellung.
**** Die Sicherheitsgruppe ermöglicht Datenverkehr aus den für die Bereitstellung verwendeten Subnetzen, insbesondere HTTPS- (443) und iSCSI- (3260) TCP-Ports.




.. *Snapshot Policy*: Standardmäßig aktiviert. Snapshots werden täglich erstellt und haben eine Aufbewahrungsfrist von 7 Tagen.
+
Die Snapshots werden Volumes zugewiesen, die für PostgreSQL-Workloads erstellt wurden.

.. *Größe des Datenlaufwerks*: Geben Sie die Kapazität des Datenlaufwerks ein und wählen Sie die Kapazitätseinheit aus.
.. *Bereitgestellte IOPS*: Wählen Sie *automatisch* oder *vom Benutzer bereitgestellt*. Wenn Sie *User-provisioned* auswählen, geben Sie den IOPS-Wert ein.
.. *Durchsatzkapazität*: Wählen Sie die Durchsatzkapazität aus dem Dropdown-Menü.
+
In bestimmten Regionen können Sie eine Durchsatzkapazität von 4 Gbit/s wählen. Um eine Durchsatzkapazität von 4 GB/s bereitzustellen, muss Ihr FSX für ONTAP-Dateisystem mit mindestens 5,120 gib SSD-Speicherkapazität und 160,000 SSD-IOPS konfiguriert werden.

.. *Verschlüsselung*: Wählen Sie einen Schlüssel aus Ihrem Konto oder einen Schlüssel aus einem anderen Konto. Sie müssen den Verschlüsselungsschlüssel ARN von einem anderen Konto eingeben.
+
Die benutzerdefinierten FSX for ONTAP-Schlüssel werden basierend auf der Serviceinführbarkeit nicht aufgeführt. Wählen Sie einen geeigneten FSX-Verschlüsselungsschlüssel aus. Nicht-FSX-Verschlüsselungen verursachen Fehler bei der Servererstellung.

+
Von AWS gemanagte Schlüssel werden nach Servicetauglichkeit gefiltert.

.. *Tags*: Optional können Sie bis zu 40 Tags hinzufügen.
.. *Simple Notification Service*: Optional können Sie den Simple Notification Service (SNS) für diese Konfiguration aktivieren, indem Sie ein SNS-Thema für Microsoft SQL Server aus dem Dropdown-Menü auswählen.
+
... Aktivieren Sie den Simple Notification Service.
... Wählen Sie im Dropdown-Menü ein ARN aus.


.. *CloudWatch Monitoring*: Optional können Sie CloudWatch Monitoring aktivieren.
+
Wir empfehlen die Aktivierung von CloudWatch zum Debuggen im Fehlerfall. Die Ereignisse, die in der AWS CloudFormation-Konsole angezeigt werden, haben eine hohe Ebene und geben nicht die Ursache an. Alle detaillierten Protokolle werden im Ordner in den EC2-Instanzen gespeichert `C:\cfn\logs` .

+
In CloudWatch wird eine Protokollgruppe mit dem Namen des Stacks erstellt. Unter der Protokollgruppe wird ein Protokollstrom für jeden Validierungs-Node und jeden SQL-Node angezeigt. CloudWatch zeigt den Skriptfortschritt an und liefert Informationen, um zu verstehen, ob und wann die Bereitstellung fehlschlägt.

.. *Resource Rollback*: Diese Funktion wird derzeit nicht unterstützt.


. Zusammenfassung
+
.. *Geschätzte Kosten*: Gibt eine Schätzung der Kosten an, die Ihnen entstehen könnten, wenn Sie die angezeigten Ressourcen bereitgestellt haben.


. Klicken Sie auf *Create*, um den neuen Datenbank-Host bereitzustellen.
+
Alternativ können Sie die Konfiguration speichern.



--
====
.Wie es weiter geht
Sie können Benutzer, Remote-Zugriff und Datenbanken auf dem bereitgestellten PostgreSQL-Server manuell konfigurieren.
