---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: In BlueXP  Workload Factory für Datenbanken einen Sandbox-Klon erstellen. 
---
= In BlueXP  Workload Factory für Datenbanken einen Sandbox-Klon erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mit der Erstellung eines Sandbox-Klons einer Datenbank in der BlueXP -Workload-Fabrik für Datenbanken können Sie den Klon für Entwicklung, Tests, Integration, Analysen, Training, Qualitätssicherung und mehr verwenden, ohne die Quelldatenbank zu ändern.

.Über diese Aufgabe
Aus dem letzten Snapshot auf der Quelldatenbank wird ein Sandbox-Klon erstellt. Es kann in demselben Microsoft SQL Server wie die Quelldatenbank geklont oder in einem anderen Microsoft SQL Server geklont werden, sofern sie dasselbe FSX für ONTAP Dateisystem nutzen.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie die folgenden Voraussetzungen erfüllen, bevor Sie einen Sandbox-Klon erstellen.

Anmeldeinformationen und Berechtigungen:: Sie müssen link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS-Kontoanmeldeinformationen und Berechtigungen für den Nur-Lese- oder Lese-/Schreibmodus"^]in der Workload Factory einen Sandbox-Klon erstellen.
+
--
Alternativ können Sie die Codebox verwenden, um eine teilweise abgeschlossene Vorlage zu kopieren oder eine fertige Vorlage zu erstellen, sodass Sie den Sandbox-Klon außerhalb der Workload Factory mit REST API erstellen können. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Erfahren Sie mehr über die Codebox-Automatisierung"^].

--
Microsoft SQL Server:: Sie benötigen einen verwalteten Microsoft SQL Server in der Workload-Fabrik für Datenbanken, um den neuen Sandbox-Klon zu hosten.
AWS System Manager:: Stellen Sie sicher, dass die `NT Authority\SYSTEM` Benutzerberechtigung auf dem Microsoft SQL-Host über AWS Systems Manager aktiviert ist.
Quelldatenbank:: Für den Klon benötigen Sie eine Quelldatenbank.


.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie in Datenbanken die Registerkarte *Sandboxes* aus.
. Wählen Sie auf der Registerkarte Sandboxes die Option *Neue Sandbox erstellen* aus.
. Geben Sie auf der Seite Neue Sandbox erstellen unter Datenbank-Quelle Folgendes an:
+
.. *Quelldatenbank-Host*: Wählen Sie den Quelldatenbank-Host aus.
.. *Quelldatenbankinstanz*: Wählen Sie die Quelldatenbankinstanz aus.
.. *Quelldatenbank*: Wählen Sie die Quelldatenbank aus, aus der Sie klonen möchten.


. Geben Sie unter Datenbankziel Folgendes an:
+
.. *Ziel-Datenbank-Host*: Wählen Sie einen Ziel-Datenbank-Host für den Sandbox-Klon, der in der gleichen VPC ist und hat das gleiche FSX für ONTAP-Dateisystem wie der Quell-Host.
.. *Zieldatenbankinstanz*: Wählen Sie die Zieldatenbankinstanz für den Sandbox-Klon aus.
.. *Zieldatenbank*: Geben Sie einen Namen für den Sandbox-Klon ein.


. *Mount*: Beim Klonen einer SQL-Datenbank, die mehrere Daten und/oder Protokolldateien enthält, klont Workload Factory alle Dateien unter dem automatisch zugewiesenen oder definierten Laufwerksbuchstaben.
+
Wählen Sie eine der folgenden Optionen:

+
.. *Mount-Punkt automatisch zuweisen*
.. *Pfad für Mount-Punkt definieren*
+
Geben Sie Folgendes an, um den Pfad des Bereitstellungspunkts zu definieren:

+
*** Geben Sie den Laufwerkbuchstaben für den Pfad der Datendatei ein.
*** Geben Sie den Laufwerksbuchstaben für den Pfad der Protokolldatei ein.




. *Tag definieren*: Wählen Sie ein Tag, um den Sandbox-Klon zu definieren.
. Klicken Sie Auf *Erstellen*.


Um den Fortschritt des Jobs zu überprüfen, wechseln Sie zur Registerkarte *Job-Überwachung*.
