---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen für die BlueXP -Workload-Fabrik für Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Unterstützung der Instanzerkennung

Workload Factory unterstützt die Erkennung von PostgreSQL-Instanzen, die nur auf Amazon Linux-Betriebssystemen ausgeführt werden, und Oracle-Instanzen, die nur auf Red Hat Enterprise Linux ausgeführt werden.



== Unterstützung für AMI-Bildversionen

Für jede SQL-Version werden nur bis zu vier aktuelle Versionen oder Revisionen von AMI-Images angezeigt. Wir lassen die Installation von einem AMI-Image, das älter als die letzten vier Versionen ist, nicht zu.



== Benutzerdefinierte AMI

Die Bereitstellung mit einem benutzerdefinierten AMI setzt voraus, dass Installationsmedien im Image vorhanden sind. Dies ist für die FCI-Konfiguration aus folgenden Gründen erforderlich:

* Deinstallieren und Neukonfigurieren des FCI-Clusters
* Wenn Sie eine andere Sammlung als die Sammlung im Image für die eigenständige Bereitstellung auswählen


Im Rahmen der Bereitstellung installiert Workload Factory keine benutzerdefinierte AMI mit mehreren Microsoft SQL Server Instanzen. Nur die Standardinstanz von Microsoft SQL Server ist ausgewählt und als Teil der Bereitstellung konfiguriert.



== Führen Sie ein Rollback durch und versuchen Sie es erneut, wenn Bereitstellungen fehlgeschlagen sind

Rollback und erneute Versuche für fehlgeschlagene Bereitstellungen werden in der Workload-Fabrik nicht unterstützt. Sie können ein Rollback durchführen oder einen fehlgeschlagenen Stack von der CloudFormation-Konsole in AWS erneut versuchen.



== Rollback von Active Directory- und DNS-Ressourcen

Die folgenden DNS-Ressourcen werden beim Rollback eines Tests oder einer fehlgeschlagenen Bereitstellung von der CloudFormation-Konsole in AWS nicht aus Active Directory und DNS entfernt:

* Jeder Knoten der SQL-Bereitstellung an seine Management-IP-Adresse
* Windows-Cluster-Name für die reservierten sekundären IP-Adressen von EC2-Instanzen in FCI-Fällen
* SQL FCI-Name zu den beiden reservierten IP-Adressen von beiden EC2-Instanzen in FCI


Sie müssen diese manuell bereinigen oder warten, bis die Domäne veraltete Einträge löscht.



== Always-On-Konfiguration von Verfügbarkeitsgruppen

Die Verwaltung von Konfigurationen für „Always On“-Verfügbarkeitsgruppen wird in der Workload-Werkseinstellung nicht unterstützt.



== Benutzerdefinierte Verschlüsselung

Benutzerdefinierte Verschlüsselungsschlüssel für FSX for ONTAP werden gemäß der Service-Anwendbarkeit nicht aufgeführt. Sie müssen den entsprechenden Schlüssel auswählen. Managed Keys in AWS werden nach der Anwendbarkeit des Services gefiltert.



== CloudFormation-Vorlage

Eine heruntergeladene oder kopierte, von der Codebox generierte CloudFormation-Vorlage (YAML-Datei) hat eine begrenzte Aufbewahrungsfrist von sieben Tagen.



== Sandbox-Support

Es können maximal 90 Sandbox-Klone von einem Datenbankserver erstellt werden.



== Erkennung und Verwaltung von Microsoft SQL Server

Die Microsoft SQL Server-Erkennung wird nicht gespeichert. Bei jedem Zugriff auf Datenbanken in der Workload Factory wird die Microsoft SQL Server-Erkennung erneut ausgeführt, um SQL-Installationen in der Region zu identifizieren.



== Einsparungen entdecken

Auf der Registerkarte Inventar werden die geschätzten Kosten für jede Microsoft SQL-Instanz auf der Ebene des FSX für ONTAP-Dateisystems und nicht für Volumes, die die SQL-Instanz hosten, berechnet.



== Mehrere FSX für ONTAP-Dateisysteme

Workload Factory unterstützt nicht das Erstellen oder Speichern von Konfigurationen für Microsoft SQL Server mit mehreren FSX für ONTAP-Dateisystemen. Es wird nur eine Bereitstellung von FSX for ONTAP-Dateisystemkonfigurationen unterstützt.



== Optimierungsbeschränkungen



=== Optimierung für die Größenanpassung von Compute

Wenn Sie auf bestimmte Instanztypen wechseln, wird die Netzwerkkonfiguration möglicherweise zurückgesetzt, was dann während der Optimierung zu einem Ausfall der Knotenverbindung und einem Jobausfall führen kann. Möglicherweise sind manuelle Eingriffe erforderlich, um die DNS-Einstellung und iSCSI-Sitzungen zu überprüfen und zu aktualisieren. Weitere Informationen zu EC2-Größenbeschränkungen finden Sie unterlink:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Amazon Elastic Compute Cloud Dokumentation"^].



=== Optimierung der ONTAP- und Betriebssystemkonfiguration

Die Massenoptimierung für mehr als eine SQL Server-Instanz wird für die ONTAP-Konfiguration und die Betriebssystemkonfiguration nicht unterstützt.



=== Bewertung von Patches für das Betriebssystem zur Optimierung

Die für Optimierungszwecke vorgestellte Bewertung von Betriebssystem-Patches darf in einem privaten Netzwerk nicht funktionieren. Die Bewertung basiert auf AWS Patch Manager. Informationen zum Patchen von Windows EC2-Instanzen in einem privaten Netzwerk finden Sie unter link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["Der AWS Cloud Operations Blog „How to Patch Windows EC2 Instances in private Subnets using AWS Systems Manager“"^].



== Lokale Einsparungsberechnung

Kosten- und prozentuale Einsparungen Berechnungen der Volume-Größe für lokalen Storage mit Microsoft SQL Server werden nicht berücksichtigt.



== Regionsübergreifende Replizierungsbewertung

* Die Optimierungsbewertung kann nicht ermitteln, ob regionsübergreifende Replizierung (CRR) verwendet wird, wenn sich das Ziel-Filesystem FSX für ONTAP in einem anderen AWS-Konto befindet.
* Workload Factory bewertet nur die CRR-Konfiguration des Quell-FSX für ONTAP-Dateisystem.

