---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory für Datenbanken ist ein End-to-End-Service für die Bereitstellung und Wartung von Datenbanken mit integrierten Best Practices für Optimierung, automatisches Thin Cloning sowie Überwachungs- und Problemlösungsfunktionen. 
---
= Erfahren Sie mehr über NetApp Workload Factory für Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory für Datenbanken ist ein End-to-End-Service für die Bereitstellung und Wartung von Datenbanken mit integrierten Best Practices für Optimierung, automatisches Thin Cloning sowie Überwachungs- und Problemlösungsfunktionen.



== Was ist NetApp Workload Factory für Datenbanken?

NetApp Workload Factory für Datenbanken erkennt, bewertet, plant, stellt bereit und verschiebt Microsoft SQL Server-Daten zu Amazon FSx for NetApp ONTAP Bereitstellungen (FSx für ONTAP), die optimiert sind, um Ihre Leistungs- und Kostenerwartungen zu erfüllen und gleichzeitig die Best Practices der Branche einzuhalten.  Während des gesamten Lebenszyklus bietet NetApp Workload Factory for Databases kontinuierliche Optimierung und Verwaltung für Datenbanken auf FSx for ONTAP.

Weitere Informationen zu Workload Factory finden Sie imlink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Übersicht über Workload Factory"^] .



== Vorteile von Workload Factory für selbstverwaltete Datenbanken

Workload Factory bietet die folgenden nützlichen Best Practices und Automatisierungen für selbstverwaltete Datenbanken.



=== Best Practices in sich vereint

* Integrierte Kenntnisse aus AWS Cloud, Microsoft Windows und SQL Server sowie NetApp ONTAP für SQL Server-Implementierungen auf EC2 Instanzen.
* Für TCO optimierte Bereitstellung.
* Automatisierung der End-to-End-Implementierung gemäß den Best Practices von AWS, Microsoft und ONTAP
* Der Bereitstellungsmodus „Schnell erstellen“ hilft Ihnen, potenzielle Fallstricke bei der manuellen Konfiguration zu vermeiden.




=== Automatisierung mit Workload Factory Codebox

Workload Factory führt mit der _Codebox_ eine integrierte Automatisierung ein.  Die Codebox bietet folgende Automatisierungsvorteile:

* *Code Snippet Generation*: Infrastructure-as-Code (IAC) Snippets werden während der Ressourcenerstellung erzeugt, was eine nahtlose Integration in bestehende Orchestrierungs-Workflows ermöglicht.
* *Infrastructure-as-Code-Copilot*: Die Codebox ist ein Infrastructure-as-Code-Copilot (IaC), der Entwicklern und DevOps dabei hilft, Code zu generieren, um alle von Workload Factory unterstützten Vorgänge auszuführen.
* *Code-Viewer und Automations-Katalog*: Die Codebox bietet einen Code-Viewer für die schnelle Analyse der Automatisierung und einen Automatisierungs-Katalog für eine schnelle spätere Wiederverwendung.




=== Funktionen von Workload Factory für Datenbanken

Workload Factory für Datenbanken bietet die folgenden Funktionen:

* *Einfache, schnelle Bereitstellungen*: Vereinfachen und optimieren Sie Ihre Bereitstellungserfahrung, indem Sie Antworten auf Spezifikationsfragen auswählen und die normalerweise erforderliche Zeit für die Untersuchung der Bereitstellung und Konfiguration Ihres Microsoft SQL Server auf AWS vermeiden.
* *Automatisierte Orchestrierung*: verfügbar über die Workload Factory-Konsole mit den Bereitstellungsmodi „Schnell“ und „Erweitert“, den Chatbot und AWS CloudFormation über die Codebox.
* *Integrierte Funktionen*: Nutzen Sie Best Practices für NetApp, Microsoft und Amazon sowie die in die Bereitstellungskonfiguration integrierte Auswahl an AWS-Ressourcen.
* *Kostenschätzung*: Bewerten Sie die potenziellen Kosteneinsparungen mit dem Einsparungsrechner, der die Kosten für Storage, Compute, SQL-Lizenzierung, Snapshots und Klonen in Einzelposten für bestehende Microsoft SQL Server-Implementierungen mit Elastic Block Store und FSX für Windows-Dateiserver im Vergleich zu FSX für ONTAP schätzt und detailliert beschreibt.
* *Wiederverwendbare Automatisierungsvorlagen*: Erstellen, wiederverwenden und passen Sie CloudFormation-Vorlagen aus der Workload Factory Codebox für zukünftige Microsoft SQL Server-Bereitstellungen in mehreren Umgebungen an.
* *Ermittlung und Bereitstellung von AWS-Ressourcen*: Automatische Erkennung von Microsoft SQL-Servern auf FSX für ONTAP, FSX für Windows-Dateiserver und Elastic Block Store, die über Ihr AWS-Konto bereitgestellt werden. Der Datenbankbestand dient als Ausgangspunkt für die Erkundung von Einsparungsmöglichkeiten für Server in anderen AWS Storage-Systemen oder eines Management-Tools für FSX für ONTAP-basierte Server und Instanzen.
* *Sandbox-Erstellung*: Erstellen Sie eine isolierte On-Demand-Datenbankumgebung, die für Tests, Integration, Diagnose und Schulung verwendet werden kann, ohne die Produktionsdaten zu beeinträchtigen.
* *Datenbankerstellung*: Erstellen Sie eine Benutzerdatenbank für Ihre vorhandenen Microsoft SQL Server mit _Quick_ oder _Advanced_ create Modi, um Ihre Datenbanksortierung, Dateinamen und Größen zu konfigurieren. Die Speicherkonfiguration ist inbegriffen.
* *Job Monitoring*: Überwachen und verfolgen Sie den Fortschritt der Ausführung von Datenbankjobs und diagnostizieren und beheben Sie Probleme, falls ein Fehler auftritt.
* *Kontinuierliche Optimierung*: Scannt kontinuierlich Ihre Microsoft SQL Server-Anlage offline und bietet Ihnen einen umfassenden Bericht mit Einblicken, Möglichkeiten und Empfehlungen, um Ihnen zu helfen, betriebliche Spitzenleistungen zu erzielen.




== Vorteile von Amazon FSX for ONTAP für selbst gemanagte Datenbanken

* *Langlebigkeit, Verfügbarkeit und Zuverlässigkeit*: FSX for ONTAP bietet mehrere Funktionen, die die Haltbarkeit und Verfügbarkeit von selbst gemanagten Datenbanken verbessern, die auf FSX for ONTAP gehostet werden. Dazu gehören Hochverfügbarkeit mit Unterstützung für einzelne und mehrere Verfügbarkeitszonen-Bereitstellungen, applikationsspezifische Snapshots, verbesserte Disaster Recovery durch Replikation und effizientes Backup.
* *Performance und Skalierbarkeit*: FSX für ONTAP bietet Performance-Optimierung mit hohem Durchsatz, niedriger Latenz, High-Speed-Netzwerkverbindungen und Skalierbarkeit mit mehreren Filesystemen für die Skalierung der aggregierten Performance, die für einen Workload erforderlich ist.
* *Datenmanagement und Effizienz*: FSX for ONTAP bietet verschiedene Funktionen zur Verbesserung von Datenmanagement und Effizienz, z. B. platzsparende Thin Clones, Thin Provisioning, Komprimierung und Deduplizierung sowie Tiering selten genutzter Daten in den Kapazitäts-Pool.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Erfahren Sie mehr über FSx for ONTAP für Workload Factory"^] .



== Tools zur Verwendung von NetApp Workload Factory

Sie können NetApp Workload Factory mit den folgenden Tools verwenden:

* *Workload Factory-Konsole*: Die Workload Factory-Konsole bietet eine visuelle, ganzheitliche Ansicht Ihrer Anwendungen und Projekte.
* * NetApp Konsole*: Die NetApp Konsole bietet eine hybride Benutzeroberfläche, sodass Sie Workload Factory zusammen mit anderen NetApp -Datendiensten verwenden können.
* *Fragen Sie mich*: Verwenden Sie den KI-Assistenten „Fragen Sie mich“, um Fragen zu stellen und mehr über Workload Factory zu erfahren, ohne die Workload Factory-Konsole zu verlassen. Greifen Sie über das Hilfemenü von Workload Factory auf „Fragen Sie mich“ zu.
* *CloudShell CLI*: Workload Factory enthält eine CloudShell CLI zum Verwalten und Betreiben von AWS- und NetApp -Umgebungen über Konten hinweg von einer einzigen, browserbasierten CLI aus. Greifen Sie über die obere Leiste der Workload Factory-Konsole auf CloudShell zu.
* *REST-API*: Verwenden Sie die Workload Factory REST-APIs, um Ihre FSx für ONTAP Dateisysteme und andere AWS-Ressourcen bereitzustellen und zu verwalten.
* *CloudFormation*: Verwenden Sie AWS CloudFormation-Code, um die Aktionen auszuführen, die Sie in der Workload Factory-Konsole definiert haben, um AWS- und Drittanbieterressourcen aus dem CloudFormation-Stack in Ihrem AWS-Konto zu modellieren, bereitzustellen und zu verwalten.
* *Terraform NetApp Workload Factory-Anbieter*: Verwenden Sie Terraform, um in der Workload Factory-Konsole generierte Infrastruktur-Workflows zu erstellen und zu verwalten.




== Unterstützte Konfigurationen

Workload Factory unterstützt die folgenden Datenbank-Engines, Versionen, Betriebssysteme und Bereitstellungsmodelle gemäß den Best Practices von AWS, NetApp ONTAP, Microsoft SQL Server, Oracle und PostgreSQL.

[cols="1,1,1,1"]
|===
| Motor | Version | Betriebssystem | Bereitstellungsmodell 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2017 | Beliebig | FCI, Einzelinstanz 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Beliebig | FCI, Einzelinstanz 


| Orakel | 19c | RHEL, SuSe Linux | Standalone (Einzel-/Mehrere Mandanten) 


| Orakel | 21c | RHEL, SuSe Linux | Standalone (Einzel-/Mehrere Mandanten) 


| Orakel | 19c | RHEL, SuSe Linux | Standalone (Einzel-/Mehrere Mandanten) 


| Orakel | 21c | RHEL, SuSe Linux | Standalone (Einzel-/Mehrere Mandanten) 


| Orakel | 19c | RHEL, SuSe Linux | Standalone mit ASM (Single/Multi Tenant) 


| Orakel | 21c | RHEL, SuSe Linux | Standalone mit ASM (Single/Multi Tenant) 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA, eigenständige Instanz 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA, eigenständige Instanz 
|===


== Integrierte AWS Services

Datenbanken umfassen die folgenden integrierten AWS-Services:

* CloudFormation
* Simple Notification Service
* CloudWatch
* System Manager
* Secrets Manager




== Regionen

Datenbanken werden in allen kommerziellen Regionen unterstützt, in denen FSX for ONTAP unterstützt wird. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Unterstützte Amazon Regionen anzeigen."^]

Die folgenden AWS Regionen werden nicht unterstützt:

* China-Regionen
* GovCloud (USA) Regionen
* Geheime Cloud
* Top Secret Cloud




== Hilfe wird abgerufen

Amazon FSX für NetApp ONTAP ist eine AWS-First-Party-Lösung. Wenn Sie Fragen oder Probleme des technischen Supports im Zusammenhang mit Ihrem FSX für ONTAP-Filesystem, Ihrer Infrastruktur oder jeder Lösung, die diesen Service verwendet, verwenden Sie das Support-Center in Ihrer AWS-Managementkonsole, um einen Support-Fall für AWS zu eröffnen. Wählen Sie den Service „FSX for ONTAP“ und die entsprechende Kategorie aus. Geben Sie die verbleibenden Informationen an, die zur Erstellung Ihres AWS-Supportfalls erforderlich sind.

Allgemeine Fragen zu Workload Factory oder Workload Factory-Anwendungen und -Diensten finden Sie unterlink:get-help.html["Hilfe zu NetApp Workload Factory für Datenbanken"] .
