---
sidebar: sidebar 
permalink: manage-instance.html 
keywords: host instance, instance management, FSx for ONTAP, instance, manage host, view host, database host, database instance, manage 
summary: Erfahren Sie mehr über die Instanzverwaltung in der Workload Factory für Datenbanken. 
---
= Instanzverwaltung in der Workload Factory für Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die Verwaltung registrierter Hostinstanzen in der Workload Factory umfasst die Bereitstellung von Ressourcen für Ihre Instanzen, wie das Erstellen von Datenbanken und Datenbankklonen, sowie die Überwachung von Instanz- und Datenbankstatus, Ressourcenauslastung, Schutz und Speicherleistung. Darüber hinaus können Sie den Status Ihrer Datenbankkonfigurationen analysieren und Best Practices für die Konfiguration implementieren, um die Leistung zu verbessern und die Betriebskosten zu senken. Die Instanzverwaltung ist nur für Instanzen mit FSx für ONTAP-Dateisystemspeicher verfügbar.

Sie müssen link:register-instance.html["Registrieren einer Hostinstanz"] um eine der folgenden Verwaltungsaufgaben auszuführen.

Zu den Managementaufgaben gehören:

* link:create-database.html["Erstellen einer Datenbank"]
* link:create-sandbox-clone.html["Erstellen eines Datenbankklons (Sandbox)"]
* link:view-databases.html["Datenbanken anzeigen"]
* link:optimize-configurations.html["Implementierung gut konzipierter Datenbankkonfigurationen"]

