---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: NetApp Workload Factory für Datenbanken scannt Microsoft SQL Server-Konfigurationen und liefert Erkenntnisse und Empfehlungen, die Ihnen dabei helfen, betriebliche Höchstleistungen zu erzielen. 
---
= Implementieren Sie gut strukturierte Datenbankkonfigurationen in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Nutzen Sie die Erkenntnisse und Empfehlungen der Konfigurationsanalyse und implementieren Sie mit NetApp Workload Factory Best Practices für Ihre Datenbankkonfigurationen mit Microsoft SQL Server und Oracle. Sie können den Status der ordnungsgemäßen Architektur problemlos überprüfen, sich über Probleme mit Datenbankkonfigurationen informieren und Maßnahmen ergreifen, um Konfigurationen zu verbessern, die nicht hinsichtlich Zuverlässigkeit, Sicherheit, Effizienz, Leistung und Kosten optimiert sind.

Sie können die Analyse bestimmter Konfigurationen, die nicht auf Ihre Umgebung zutreffen, auch ablehnen, um unnötige Warnungen und ungenaue Optimierungsergebnisse zu vermeiden.

link:optimize-overview.html["Erfahren Sie mehr über die Konfigurationsanalyse und den Status „Well-Architected“ in Workload Factory."]



== Über diese Aufgabe

Workload Factory analysiert täglich Datenbankkonfigurationen.  Die tägliche Analyse liefert den Status der ordnungsgemäßen Architektur sowie Erkenntnisse und Empfehlungen mit Optionen zur automatischen Behebung von Konfigurationsproblemen, sodass Ihre Konfigurationen den Best Practices entsprechen.

Sie haben die Möglichkeit, die Empfehlungen für Konfigurationsprobleme zu überprüfen und diese Probleme über das Datenbankinventar in der Workload Factory-Konsole zu beheben.

.Was analysiert wird
Workload Factory analysiert den ordnungsgemäßen Architekturstatus der folgenden Konfigurationen:

Für Microsoft SQL Server-Instanzen:

* Storage-Dimensionierung: Umfasst Storage-Tier, File-System-Reserve, Größe des Protokolllaufwerks und Größe des tempdb-Laufwerks
* Speicherlayout: Beinhaltet die Platzierung von Benutzerdatendateien, die Platzierung von Protokolldateien und die Platzierung von tempdb
* Speicherkonfiguration: umfasst Kapazitätsverwaltung, Thin Provisioning, Tiering-Richtlinie, Snapshots, Microsoft Multipath I/O (MPIO)-Status und MPIO-Timeout-Einstellung
* Compute: umfasst Rightsizing, Betriebssystem-Patches und Netzwerkadaptereinstellungen wie Receive Side Scaling (RSS), TCP-Offloading und MTU-Ausrichtung
* Anwendungen: Enthält Microsoft SQL Server-Lizenzen, Microsoft SQL Server-Patch und MAXDOP-Einstellungen
* Ausfallsicherheit: umfasst lokale Snapshots, FSx für ONTAP Backups, regionsübergreifende Replikation (CRR) und Microsoft SQL High Availability.
* Klone: Enthält Optionen zum Aktualisieren und Löschen von Klonen (Sandboxen), die innerhalb oder außerhalb der Workload Factory erstellt wurden und älter als 60 Tage sind


Für Oracle-Datenbanken:

* Speicherkonfiguration: umfasst Kapazitätsmanagement, Thin Provisioning, Tiering-Richtlinien, Snapshots, Speichereffizienz und Betriebssystemkonfigurationen für Bereitstellungen mit NFS oder iSCSI mit oder ohne Automatic Storage Management (ASM) einschließlich Microsoft Multipath I/O (MPIO)-Status und -Einstellungen
* Speicherlayout: umfasst die Platzierung von Redo-Protokollen, temporären Tablespaces, Datendateien, Archivprotokollen, Steuerdateien und Binärdateien sowie die LUN-Anzahl der ASM-Datenträgergruppen




== Bevor Sie beginnen

* Du musstlink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Berechtigungen für Operationen und Behebung gewähren"^] in Ihrem AWS-Konto.
* Um den Speicher einer Microsoft SQL Server-Instanz oder Oracle-Datenbank zu bewerten, muss die Ressource in Workload Factory registriert sein und der Speichertyp muss FSx für ONTAP sein.link:register-instance.html["Erfahren Sie, wie Sie Ressourcen registrieren."]
* Überprüfen Sie jede Empfehlung sorgfältig, bevor Sie eine Einstellung oder Konfiguration korrigieren. Für RSS- und MAXDOP-Einstellungen empfehlen wir, die empfohlenen Einstellungen zu testen, um Leistungsverbesserungen zu ermitteln, bevor Sie Änderungen an Ihrer Produktionsumgebung vornehmen.



NOTE: Die Problembehebung kann zu Ausfallzeiten von Instanzen oder Serviceunterbrechungen führen. Lesen Sie die Empfehlung sorgfältig durch, bevor Sie sich für die Korrektur einer Konfiguration entscheiden.



== Beheben eines Konfigurationsproblems

Beheben Sie Konfigurationsprobleme für SQL Server- oder Oracle-Umgebungen, die auf FSx für ONTAP -Speicher ausgeführt werden.


NOTE: Der Behebungsprozess kann zu Instanzausfallzeiten oder Dienstunterbrechungen führen.  Lesen Sie die Empfehlung sorgfältig durch, bevor Sie sich für die Behebung eines Konfigurationsproblems entscheiden.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im *Inventar* den Engine-Typ aus: Microsoft SQL Server oder Oracle.
. Wählen Sie Ressourcen aus, die für bestimmte Konfigurationen repariert werden sollen.
+
** Wenn Sie Microsoft SQL Server ausgewählt haben, wählen Sie die Registerkarte *Instanzen*.
** Wenn Sie Oracle ausgewählt haben, wählen Sie die Registerkarte *Datenbanken*.


. Wählen Sie *Anzeigen und beheben* aus, um Konfigurationsprobleme für die Instanz anzuzeigen.
. Überprüfen Sie auf der Statusseite „Well-Architected“ für die Instanz die Ergebnisse der Analyse.
+
Sie können Konfigurationsprobleme nach Kategorien, Unterkategorien, Status, Schweregrad und Tags filtern.

+
Sie können auch einen Bericht mit den Ergebnissen herunterladen, indem Sie *PDF exportieren* auswählen.

. Wählen Sie den Dropdown-Pfeil aus, um die Empfehlung für eine beliebige Konfiguration anzuzeigen. Zu den Empfehlungen gehören bewährte Methoden, potenzielle Fallstricke nicht optimierter Konfigurationen und wichtige Überlegungen. Überprüfen Sie die Empfehlung sorgfältig.
. Wählen Sie „Konfigurationsprobleme anzeigen und beheben“ aus, wenn die Option verfügbar ist.
+
Die Standardeinstellung ist „*Alles auswählen*“, Sie können jedoch auch bestimmte Ressourcen zur Reparatur auswählen.

+
.. Lesen Sie für alle Konfigurationen außer der Klonbereinigung die Empfehlungsdetails, um zu erfahren, was passiert, wenn Sie sich für die Behebung des Problems entscheiden. Einige Korrekturvorgänge können zu Instanzausfallzeiten oder Dienstunterbrechungen führen.
.. Wählen Sie für die Klonbereinigung geklonte Datenbanken (Sandbox) zum Aktualisieren oder Löschen aus.
+
*** Durch das Aktualisieren eines Klons wird dieser mit seiner Quelldatenbank synchronisiert.  Die Aktualisierung ist nur für in Workload Factory erstellte Klone verfügbar.
*** Durch das Löschen eines Klons wird dieser dauerhaft entfernt, Speicherplatz freigegeben und die Kosten gesenkt.  Sie können innerhalb und außerhalb von Workload Factory erstellte Klone löschen.




. Wählen Sie *Weiter*, um das Konfigurationsproblem zu beheben.


.Ergebnis
Workload Factory beginnt mit der Behebung des/der Problems/Probleme.  Wählen Sie die Registerkarte *Jobüberwachung*, um den Status des Vorgangs anzuzeigen.



== Verschieben oder verwerfen Sie die Analyse von Datenbankkonfigurationen

Verschieben oder verwerfen Sie die Analyse bestimmter Datenbankkonfigurationen, die nicht für Ihre Datenbankumgebung gelten, um unnötige Warnmeldungen und ungenaue Optimierungsergebnisse zu vermeiden. Sie können eine verschobene oder zurückgeschobene Konfigurationsanalyse jederzeit wieder aktivieren.

Die Anwendungsanforderungen für Datenbankkonfigurationen variieren.  Workload Factory bietet Ihnen zwei Optionen zum Überspringen der Analyse bestimmter Datenbankkonfigurationen, sodass Sie nur relevante Probleme überwachen und einen genauen Überblick über den Zustand relevanter Konfigurationen erhalten können.  Wenn eine bestimmte Konfigurationsanalyse verschoben oder verworfen wird, wird die Konfiguration nicht in die Gesamtpunktzahl der Optimierung einbezogen.

Sie können die Konfigurationsanalyse auf Konfigurationsebene und auf der Ebene der SQL Server-Instanz oder der Oracle-Datenbank verschieben, ablehnen und erneut aktivieren.

* *30 Tage verschieben*: Eine Verschiebung der Analyse wird die Analyse für 30 Tage beenden. Nach 30 Tagen wird die Analyse automatisch neu gestartet.
* *Abweisen*: Das Ablehnen der Analyse verschiebt die Analyse auf unbestimmte Zeit. Sie können die Analyse bei Bedarf neu starten.


Die folgenden Anweisungen beschreiben, wie Sie eine Analyse auf Konfigurationsebene verschieben, verwerfen oder reaktivieren.  Um die folgenden Aufgaben für bestimmte SQL Server-Instanzen oder Oracle-Datenbanken abzuschließen, beginnen Sie auf der Registerkarte *Dashboard*.

[role="tabbed-block"]
====
.Verschieben
--
Verschieben, um eine Konfigurationsanalyse für 30 Tage zu stoppen. Nach 30 Tagen wird die Analyse automatisch neu gestartet.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im Menü „Datenbanken“ die Option „Inventar“ aus.
. Wählen Sie im Inventar den Datenbank-Engine-Typ aus: *Microsoft SQL Server* oder *Oracle*.
. Navigieren Sie zur SQL Server-Instanz oder Oracle-Datenbank mit der zu verschiebenden Konfiguration, wählen Sie das Aktionsmenü und dann *Gut konzipiert*.
. Scrollen Sie auf der Well-Architected-Analyseseite nach unten zur zu verschiebenden Konfiguration, wählen Sie das Aktionsmenü und dann *Verwerfen* aus.
. Wählen Sie im Konfigurationsdialogfeld „Verwerfen“ die Option „30 Tage verschieben“ und dann „Verwerfen“ aus.


.Ergebnis
Die Konfigurationsanalyse hält 30 Tage an.

--
.Verwerfen
--
Schließen, um eine Konfigurationsanalyse auf unbestimmte Zeit zu beenden. Sie können die Analyse bei Bedarf neu starten.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im Menü „Datenbanken“ die Option „Inventar“ aus.
. Wählen Sie im Inventar den Datenbank-Engine-Typ aus: *Microsoft SQL Server* oder *Oracle*.
. Navigieren Sie zur SQL Server-Instanz oder Oracle-Datenbank mit der zu verschiebenden Konfiguration, wählen Sie das Aktionsmenü und dann *Gut konzipiert*.
. Scrollen Sie auf der Well-Architected-Analyseseite nach unten zur zu verschiebenden Konfiguration, wählen Sie das Aktionsmenü und dann *Verwerfen* aus.
. Wählen Sie im Konfigurationsdialogfeld „Verwerfen“ die Option „Verwerfen“ und anschließend „Verwerfen“ aus, um das Verwerfen zu bestätigen.


.Ergebnis
Die Konfigurationsanalyse wird beendet.

--
.Reaktivieren
--
Aktivieren Sie eine verschobene oder abgeschobene Konfigurationsanalyse jederzeit erneut.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im Menü „Datenbanken“ die Option „Inventar“ aus.
. Wählen Sie im Inventar den Datenbank-Engine-Typ aus: *Microsoft SQL Server* oder *Oracle*.
. Navigieren Sie zur SQL Server-Instanz oder Oracle-Datenbank mit der zu verschiebenden Konfiguration, wählen Sie das Aktionsmenü und dann *Gut konzipiert*.
. Wählen Sie auf der Seite „Well-Architected-Analyse“ *Abgelehnte Konfiguration* aus, um nur abgelehnte Konfigurationen anzuzeigen.
. Wählen Sie *Reaktivieren*, um die Konfigurationsanalyse für die verschobene oder verworfene Konfiguration neu zu starten.


.Ergebnis
Die Konfigurationsanalyse wird reaktiviert und findet täglich im Vorwärtslauf statt.

--
====