---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory für Datenbanken analysiert regelmäßig Microsoft SQL Server- und Oracle-Konfigurationen, um festzustellen, ob Probleme vorliegen. 
---
= Konfigurationsanalyse für Datenbankumgebungen in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases analysiert regelmäßig Datenbankkonfigurationen, um festzustellen, ob es Probleme mit Microsoft SQL Server- und Oracle-Bereitstellungen auf Amazon FSx for NetApp ONTAP Speicher gibt.  Wenn Probleme gefunden werden, zeigt Ihnen Workload Factory, um welche Probleme es sich handelt, und erklärt, was geändert werden muss, um sicherzustellen, dass Ihre Datenbankkonfigurationen Spitzenleistung, Kosteneffizienz und die Einhaltung bewährter Methoden erreichen.

Die wichtigsten Funktionen:

* Tägliche Konfigurationsanalyse
* Automatische Validierung von Best Practices
* Empfehlungen zur Größenanpassung
* Proaktive Beobachtbarkeit
* Einblick in Aktion
* AWS hat eine gut konzipierte Framework Advisor Architektur




== Komponenten der Konfigurationsanalyse

Die Konfigurationsanalyse umfasst folgende Komponenten:

Zustand der Architektur gut:: Der Status „gut architektonisch“ bezieht sich auf den allgemeinen Zustand Ihrer Datenbankkonfigurationen; Konfigurationen werden in die Kategorien „optimiert“, „nicht optimiert“ oder „überdimensioniert“ eingeteilt. Der Status einer gut strukturierten Konfiguration wird innerhalb einer Microsoft SQL Server-Instanz oder einer Oracle-Datenbank in der Workload Factory-Konsole referenziert.
Gut konzipierte Punktzahl:: Die Punktzahl umfasst alle aktuell analysierten Konfigurationen und wird als Prozentsatz angezeigt. Ein Wert von 25 % bedeutet, dass 25 % Ihrer Datenbankimplementierungen gut architektonisch gestaltet sind. Der Wert für die gute Architektur wird auf dem Bildschirm *Gute Architektur* und innerhalb einer Microsoft SQL Server-Instanz oder Oracle-Datenbank in der Workload Factory-Konsole angezeigt.
Konfigurationskategorien:: Die Konfigurationen sind in folgende Kategorien unterteilt: Speicher, Rechenleistung, Anwendung, Ausfallsicherheit und Klonen. Jede Kategorie umfasst spezifische Konfigurationsbewertungen, die regelmäßig analysiert werden. Die Konfigurationskategorien werden sowohl vom Bildschirm *Well-architected* als auch innerhalb einer Microsoft SQL Server-Instanz oder einer Oracle-Datenbank in der Workload Factory-Konsole referenziert.




== Analyseumfang

Je nachdem, welche Komponente bewertet wird, ist der Optimierungsumfang unterschiedlich. Die Storage-Optimierung findet beispielsweise auf der Ebene der SQL Instanzen statt, während die Computing-Optimierung auf Host-Ebene erfolgt.



== Analyseanforderungen

Für eine vollständige Analyse der Datenbankumgebung müssen die Ressourcen registriert und online sein.

link:register-instance.html["Erfahren Sie, wie Sie Ressourcen registrieren."]

.Wie es weiter geht
link:optimize-configurations.html["Implementieren Sie gut konzipierte Datenbankkonfigurationen"]
