---
settings:
  name: Database workloads
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Dokumentation zu Datenbank-Workloads
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/known-limitations.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Workload Factory für Datenbanken
      url: "/learn-databases.html"
    - title: Schnellstart
      url: "/quick-start-databases.html"
  - title: Workload Factory für Datenbank-Workloads nutzen
    entries:
    - title: Einsparungen entdecken
      url: "/explore-savings.html"
    - title: Datenbankressourcen erstellen
      entries:
      - title: Erstellen Sie Microsoft SQL Server
        url: "/create-database-server.html"
      - title: PostgreSQL-Server erstellen
        url: "/create-postgresql-server.html"
      - title: Erstellen Sie eine Datenbank
        url: "/create-database.html"
      - title: Sandbox-Klon erstellen
        url: "/create-sandbox-clone.html"
    - title: Ressourcen verwalten
      entries:
      - title: Ressourcenmanagement
        url: "/manage-instance.html"
      - title: Ressourcen registrieren
        url: "/register-instance.html"
      - title: Management von Klonen
        url: "/manage-clones.html"
      - title: Aufheben der Registrierung von Ressourcen
        url: "/deregister-instance.html"
  - title: Datenbankressourcen schützen, überwachen und optimieren
    entries:
    - title: Fehlerprotokolle analysieren
      url: "/analyze-error-logs.html"
    - title: Implementieren von Best Practices für die Konfiguration
      entries:
      - title: Konfigurationsanalyse für Datenbanken
        url: "/optimize-overview.html"
      - title: Implementieren Sie gut konzipierte Datenbankkonfigurationen
        url: "/optimize-configurations.html"
    - title: Überwachen von Datenbankjobs
      url: "/monitor-databases.html"
    - title: Schützen Sie Microsoft SQL Server-Workloads
      url: "/protect-sql-server.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
