---
settings:
  name: Database workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation zu Datenbank-Workloads
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/known-limitations.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Workload Factory für Datenbanken
      url: "/learn-databases.html"
    - title: Schnellstart
      url: "/quick-start-databases.html"
  - title: Verwenden Sie Datenbank-Workloads
    entries:
    - title: Einsparungen entdecken
      url: "/explore-savings.html"
    - title: Erstellen Sie einen neuen Datenbankserver
      url: "/create-database-server.html"
    - title: Einen Datenbankserver erkennen
      url: "/detect-host.html"
    - title: Erstellen Sie eine Datenbank
      url: "/create-database.html"
    - title: Mit Codebox automatisieren
      url: "/automate-codebox.html"
  - title: Administration und Überwachung
    entries:
    - title: Managen eines Microsoft SQL-Servers
      url: "/manage-server.html"
    - title: Management von Klonen
      entries:
      - title: Sandbox-Klon erstellen
        url: "/create-sandbox-clone.html"
      - title: Integrität eines Sandbox-Klons prüfen
        url: "/check-clone-integrity.html"
      - title: Zurücksetzen eines Sandbox-Klons
        url: "/revert-clone.html"
      - title: Aktualisierung eines Sandbox-Klons
        url: "/refresh-clone.html"
      - title: Stellen Sie eine Verbindung zur CI/CD-Pipeline her
        url: "/connect-clone-cicd.html"
      - title: Informationen zur Klonverbindung anzeigen
        url: "/view-clone-connection.html"
      - title: Sandbox-Klon teilen
        url: "/split-clone.html"
      - title: Sandbox-Klon löschen
        url: "/delete-clone.html"
    - title: Überwachen von Datenbanken
      url: "/monitor-databases.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration-databases.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help-databases.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
