---
sidebar: sidebar 
permalink: revert-clone.html 
keywords: re-baseline, revert clone, database, Microsoft SQL 
summary: 'Setzen Sie einen Datenbankklon (Sandbox) auf seine ursprüngliche Version zum Zeitpunkt der Erstellung in NetApp Workload Factory für Datenbanken zurück.' 
---
= Einen Datenbankklon in NetApp Workload Factory für Datenbanken zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Setzen Sie einen Datenbankklon (Sandbox) auf seine ursprüngliche Version zum Zeitpunkt der Erstellung in NetApp Workload Factory für Datenbanken zurück.

.Über diese Aufgabe
Wenn Sie eine Datenbank klonen, ist der Klon bei der Erstellung ein _Basis_-Klon.  Die Daten in der geklonten Datenbank sind dieselben wie in der Quelldatenbank zum Zeitpunkt der Erstellung.  Da sich die Daten in einem Datenbankklon im Laufe der Zeit ändern, möchten Sie die Daten möglicherweise auf den Ausgangswert zurücksetzen, der zum Zeitpunkt der Erstellung des Klons galt.  Dieser Vorgang wird als „Neuerstellen der Basislinie eines Klons“ bezeichnet.  Durch die Neuausrichtung eines Klons statt der Erstellung eines neuen Klons wird Speicherplatz gespart. Allerdings werden dabei alle am Datenbankklon vorgenommenen Änderungen gelöscht.

.Schritte
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie im Menü „Datenbanken“ die Option „Sandboxen“ aus.
. Wählen Sie in Sandboxen das Aktionsmenü des Datenbankklons aus, den Sie zurücksetzen möchten.
. Wählen Sie * Neu-Baseline*.
. Wählen Sie im Dialogfeld „Basislinie neu erstellen“ die Option „Basislinie neu erstellen“ aus.

