---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: Um eine Übersicht über die Datenbankressourcen in der Workload Factory zu erhalten, zeigen Sie alle Datenbanken im Datenbankbestand an. Sie können auch Datenbanken pro einzelner registrierter Instanz anzeigen. 
---
= Anzeigen von Datenbanken in der Workload Factory für Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um eine Übersicht über die Datenbankressourcen in der Workload Factory zu erhalten, zeigen Sie alle Datenbanken im Datenbankbestand an. Sie können auch Datenbanken pro einzelner registrierter Instanz anzeigen.

.Bevor Sie beginnen
* Hostinstanzen, die Datenbankressourcen enthalten, müssen über FSx für ONTAP-Dateisystemspeicher verfügen.
* Hostinstanzen müssen in der Workload Factory registriert sein. Erfahren Sie, wie man link:register-instance.html["Hostinstanzen registrieren"].


.Schritte
[role="tabbed-block"]
====
.Anzeigen von Datenbanken für eine einzelne Instanz
--
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie in Datenbanken die Registerkarte *Inventar* aus.
. Klicken Sie auf den Dropdown-Pfeil, um die Zeile des Hosts zu erweitern und seine Datenbanken anzuzeigen.
+
Der Host wird erweitert, und die Hostinstanzen werden angezeigt.

. Klicken Sie auf das drei-Punkt-Menü der Instanz, die die anzuzeigenden Datenbanken enthält.
. Wählen Sie *Datenbanken anzeigen*.


--
.Datenbanken für alle Instanzen anzeigen
--
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie in Datenbanken die Registerkarte *Inventar* aus.
. Klicken Sie auf den Dropdown-Pfeil, um die Zeile des Hosts zu erweitern und seine Datenbanken anzuzeigen.
+
Der Host wird erweitert, und die Hostinstanzen werden angezeigt.

. Klicken Sie auf das drei-Punkt-Menü der Instanz, die die anzuzeigenden Datenbanken enthält.
. Wählen Sie *Datenbanken anzeigen*.


--
====
.Ergebnis
Sie haben die Datenbankressourcen innerhalb der Workload Factory angezeigt.
