---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: Um eine Übersicht über die Datenbankressourcen in der Workload Factory zu erhalten, zeigen Sie alle Datenbanken im Datenbankbestand an. Sie können auch Datenbanken pro einzelner registrierter Instanz anzeigen. 
---
= Anzeigen von Datenbanken in der Workload Factory für Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um eine Übersicht über die Datenbankressourcen in der Workload Factory zu erhalten, zeigen Sie alle Datenbanken im Datenbankbestand an. Sie können auch Datenbanken pro einzelner registrierter Instanz anzeigen.

.Bevor Sie beginnen
* Instanzen, die Datenbankressourcen enthalten, müssen über FSx für ONTAP-Dateisystemspeicher verfügen.
* Sie müssen Instanzen in der Workload Factory registrieren, um Datenbanken anzuzeigen. Erfahren Sie, wie Sie link:register-instance.html["eine Instanz registrieren"] .


.Schritte
[role="tabbed-block"]
====
.Anzeigen von Datenbanken für eine einzelne Instanz
--
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie in Datenbanken die Registerkarte *Inventar* aus.
. Klicken Sie auf das Drei-Punkte-Menü der Instanz und wählen Sie dann *Datenbanken anzeigen*.


Auf der Registerkarte „Datenbanken“ werden Datenbanken für die einzelne Instanz angezeigt.

--
.Datenbanken für alle Instanzen anzeigen
--
. Melden Sie sich mit einem der link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^]an.
. Wählen Sie in der Kachel Datenbanken *Gehe zu Datenbank-Inventar*.
. Wählen Sie in Datenbanken die Registerkarte *Inventar* aus.
. Wählen Sie die Registerkarte *Datenbanken*.
+
Datenbanken werden für alle registrierten Instanzen angezeigt.



--
====