---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, databases, workload factory' 
summary: Informieren Sie sich über die Neuerungen bei Workload Factory für Datenbanken. 
---
= Was ist neu
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Lernen Sie die Neuerungen bei Datenbanken kennen.



== 4 August 2024



=== Verbesserungen des Einsparungsrechners

* Beschreibungen der Kostenvoranschlafe
+
Sie erfahren nun, wie die geschätzten Kosten mithilfe des Einsparungsrechners berechnet werden. Sie können mithilfe von Amazon Elastic Block Store Storage eine Beschreibung aller Berechnungen für Ihre Microsoft SQL Server Instanzen im Vergleich zur Nutzung von Amazon FSX für ONTAP Storage einsehen.

* Unterstützung der Always-On-Verfügbarkeitsgruppe
+
Datenbanken ermöglichen jetzt mit Microsoft SQL Server unter Verwendung von Amazon Elastic Block Store Kostenersparnisse für die Bereitstellung von Always-on-Verfügbarkeitsgruppen.

* Optimierung der SQL Server-Lizenzierung mit FSX für ONTAP
+
Der Datenbank-Rechner bestimmt, ob die mit Amazon Elastic Block Store verwendete SQL Lizenzversion für Ihre Datenbank-Workloads optimiert ist. Sie erhalten eine Empfehlung für die optimale SQL-Lizenz mit FSX für ONTAP Storage.

* Mehrere SQL Server Instanzen
+
Datenbanken ermöglichen jetzt Kosteneinsparungen bei einer Konfiguration, die mehrere Microsoft SQL Server Instanzen mithilfe von Amazon Elastic Block Store hostet.

* Anpassen der Berechnungseinstellungen
+
Sie können jetzt die Einstellungen für Microsoft SQL Server, Amazon EC2 und Elastic Block Store anpassen und die Einsparungen manuell berechnen. Mit dem Einsparungsrechner wird die beste Konfiguration basierend auf den Kosten ermittelt.



link:explore-savings.html["Mit FSX for ONTAP können Sie für Ihre Datenbank-Workloads Kosten einsparen."]



== 7 Juli 2024



=== Erstversion von Workload Factory für Datenbanken

Die erste Version umfasst die Möglichkeit, mit Amazon FSX for NetApp ONTAP als Storage-Umgebung für Ihre Datenbank-Workloads die Einsparungen zu untersuchen, Microsoft SQL-Server zu erkennen, zu managen und zu implementieren, Datenbanken zu implementieren und zu klonen und diese Jobs innerhalb der Workload Factory zu überwachen.

link:learn-databases.html["Lernen Sie Datenbanken kennen"].
